### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by memendes123** [rep4rep/rep4rep-bot#1]
i cant use node main, after i use the command, this ask again for command

**Comment by memendes123** [comment]
in my opinion best option is login with username:password:shared_secret. no more problems with steam guard, i cant login in my accounts right now :(

**Comment by fx1738** [comment]
Issue with twoFactorCode has been resolved in the latest commit. there's no support for the shared_secret however currently.

https://github.com/rep4rep/rep4rep-bot/commit/87f4a4b27d7875aa186f6614f9a5bb56585d9e06
