### ISSUE TITLE
Logs out of the accounts too frequently

### ISSUE THREAD

**Issue by DoKnocK** [rep4rep/rep4rep-bot#2]
1. Is this a normal behavior for it log out of the accounts everyday ? I have to enter credentials again literally everyday, is this normal ? Please let me know if it can be fixed with a database or something ?

2. Also, is it possible to use shared secret key for accounts with Steam Authenticator ? Would pretty much make the job easy to import accounts. 

3. And, if importing accounts from excel or text file can be done, that would also make it easy to import accounts if daily logouts cannot be fixed for some reason. 

4. How about making it skip the account right after 10 successful comments are done (just suggesting), would save some time for it to fail twice before skipping that account.

**Comment by FexileTV** [comment]
The current bot code is missing a lot of features, it also doesn't save passwords that's why accounts logout so frequently.

You are free to check what API endpoints it uses and create your own version.

I'll work on a better bot later on though that solves all the issues you listed.
